### ISSUE TITLE
Colourblindness accessibility on hobby page

### ISSUE THREAD

**Issue by gitchly** [SameGD/SameGD.github.io#2]
At https://samegd.github.io/hobbies you denote whether a hobby is finished/in progress/not started based entirely on colour. This may make it difficult for people with a colour vision deficiency to tell the status of a hobby.

Here is an example using simulated deuteranopia:

![download](https://user-images.githubusercontent.com/12066089/96330037-c8a35c80-1041-11eb-88fc-83280809429f.png)

I'd recommend using some sort of iconographic representation of completeness in addition to the colour - perhaps a small icon or emoji would do?
🔻🟡✔️

**Comment by DaneRainbird** [comment]
Seconded on this; I propose something like:

- Not started = ❌
- In Progress = 🚧 
- Finished = ✔️

**Comment by SameGD** [comment]
That's a good point, I've implemented it in the latest update.
